In [1]:
import numpy as np
import matplotlib.pyplot as plt


np.random.seed(0)
X0 = np.random.randn(20, 2)
X1 = np.random.randn(20, 2) + np.array([5, 5])
y = np.array([1] * 20 + [-1] * 20)

X = np.r_[X0, X1]

import numpy as np
from operator import itemgetter

In [2]:
a = np.zeros(X.shape[0])
ay = 0
ayx = np.zeros(X.shape[1]) # ある行に対するラグランジュ条数、目的変数(ラベル)、特徴量の掛け算/aiハッシュを計算のため
yx = y.reshape(-1, 1)*X # 目的変数(ラベル)、特徴量の掛け算/aiハッシュを計算のため
indices = np.arange(X.shape[0]) # インデックス作成 = サンプル数


In [3]:
yx

array([[ 1.76405235,  0.40015721],
       [ 0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ],
       [ 0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252],
       [-0.88778575, -1.98079647],
       [-0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985],
       [-0.38732682, -0.30230275],
       [-3.95144703, -3.57998206],
       [-3.29372981, -6.9507754 ],
       [-4.49034782, -4.5619257 ],
       [-3.74720464, -5.77749036],
       [-3.38610215, -4.78725972],
       [-4.10453344, -5.3869025 ],
       [-4.48919486, -3.81936782],
       [-4.97181777, -5.42833187],
       [-5.06651722,

In [4]:
ayx

array([0., 0.])

In [5]:
np.dot(yx, ayx.T)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [6]:
ydf = y*(1-np.dot(yx, ayx.T))
ydf

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1.])

In [7]:
iydf = np.c_[indices, ydf]
iydf

array([[ 0.,  1.],
       [ 1.,  1.],
       [ 2.,  1.],
       [ 3.,  1.],
       [ 4.,  1.],
       [ 5.,  1.],
       [ 6.,  1.],
       [ 7.,  1.],
       [ 8.,  1.],
       [ 9.,  1.],
       [10.,  1.],
       [11.,  1.],
       [12.,  1.],
       [13.,  1.],
       [14.,  1.],
       [15.,  1.],
       [16.,  1.],
       [17.,  1.],
       [18.,  1.],
       [19.,  1.],
       [20., -1.],
       [21., -1.],
       [22., -1.],
       [23., -1.],
       [24., -1.],
       [25., -1.],
       [26., -1.],
       [27., -1.],
       [28., -1.],
       [29., -1.],
       [30., -1.],
       [31., -1.],
       [32., -1.],
       [33., -1.],
       [34., -1.],
       [35., -1.],
       [36., -1.],
       [37., -1.],
       [38., -1.],
       [39., -1.]])

In [8]:
 i = int(min(iydf[(y < 0) | (a > 0)],
                        key=itemgetter(1))[0]) 
 i

20

In [9]:
j = int(max(iydf[(y > 0) | (a > 0)],
                        key=itemgetter(1))[0]) 
j

0

In [10]:
ay2 = ay - y[i]*a[i] - y[j]*a[j]
ay2

0.0

In [14]:
min(iydf[(y < 0) | (a > 0)], key=itemgetter(1))

array([20., -1.])

In [15]:
a = np.arange(12).reshape(3, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])