# 目的
- Rプログラミングの簡単な操作を習得する。
- このnotebookはR環境に変更している

### オブジェクト
- 文字や数値などを示す
- 名前をつけて保存でき、参照も可能

In [1]:
# 数字と文字の保存
x <- 1
y <- "A"

In [2]:
x + 2

[1] 3

### ベクトル: 複数の数値や文字をまとめたオブジェクト
- :, seq(). c(), rep()あたりで作成できる
- 個々の値は要素と呼ぶ
- [ は要素を取り出す演算子

In [12]:
x1 <- 1:10
print(x1)

 [1]  1  2  3  4  5  6  7  8  9 10


In [13]:
x2 <- 10:1
print(x2)

 [1] 10  9  8  7  6  5  4  3  2  1


In [15]:
z <- seq(1, 100)
print(z)
print(z[3])
print(z[10:15])

  [1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100
[1] 3
[1] 10 11 12 13 14 15


In [17]:
z1 <- c(1, 2, 3)
print(z1)

[1] 1 2 3


In [19]:
z2 <- c("a", "b", "c")
print(z2)

[1] "a" "b" "c"


In [21]:
# z3 <- c(a, b, c)
# print(z3)

ERROR: ignored

In [22]:
z4 <- rep(1, 5)
print(z4)

[1] 1 1 1 1 1


In [28]:
z5 <- rep(TRUE, 3)
print(z5)
print(mode(z5))

[1] TRUE TRUE TRUE
[1] "logical"


In [30]:
z6 <- rep("TRUE", 3)
print(z6)
print(mode(z6))

[1] "TRUE" "TRUE" "TRUE"
[1] "character"


In [31]:
z7 <- rep(seq(1, 3), 3)
print(z7)
print(mode(z7))

[1] 1 2 3 1 2 3 1 2 3
[1] "numeric"


In [34]:
z8 <- rep(seq(1, 3), each=3)
print(z8)
print(mode(z8))

[1] 1 1 1 2 2 2 3 3 3
[1] "numeric"


In [36]:
# ベクトル内部で異なるデータ型を含めた場合、多くの場合文字列で扱われる
z9 <- c(1, "a", TRUE)
print(z9)
print(mode(z9))

[1] "1"    "a"    "TRUE"
[1] "character"


### 関数
- 名前の後に丸括弧がつづく
- 丸括弧内には、引数としてオブジェクトを指定する



In [37]:
# zの合計
print(z)
print(sum(z))

  [1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100
[1] 5050


In [43]:
# 関数の定義
display_helloworld <- function(){
  "Hello, world!"
}
display_helloworld()

[1] "Hello, world!"

In [44]:
print(display_helloworld())

[1] "Hello, world!"


In [45]:
display_helloworld2 <- function(){
  print("Hello, world!")
}
display_helloworld2()

[1] "Hello, world!"


In [46]:
print(display_helloworld2())

[1] "Hello, world!"
[1] "Hello, world!"


In [48]:
# 引数の指定も可能
# 引数は省略すると既定値が実行されるが、明示的に示した方が良い
my_name <- function(name="Ikuma"){
  paste("Hi, my name is", name, "!")
}
print(my_name())
print(my_name(name="Ryuji"))
print(my_name("shohei"))

[1] "Hi, my name is Ikuma !"
[1] "Hi, my name is Ryuji !"
[1] "Hi, my name is shohei !"


### データフレーム
- 行と列の概念を持つ2次元のデータ構造
- 行もしくは列の参照には、[または$を使う
- [行、列]で参照する。入力しない場合は、全てが指定される。
- data.frame()関数で作成

In [49]:
# data.frame()でデータフレーム作成
# 引数は、列名=値の形式　で指定する

dat <- data.frame(
  X = 1:5,
  Y = seq(2, 10, by=2),
  Z = c("a", "b", "c", "d", "e")
)

print(dat)

  X  Y Z
1 1  2 a
2 2  4 b
3 3  6 c
4 4  8 d
5 5 10 e


In [50]:
print(dat[2, ])
print(dat[ , 2])
print(dat[1, 1])

  X Y Z
2 2 4 b
[1]  2  4  6  8 10
[1] 1


In [55]:
# 列名でも指定できるが文字列型なので、[なら""付き、$ならそのまま！
print(dat[, "X"])
print(dat$X)

[1] 1 2 3 4 5
[1] 1 2 3 4 5


### 行列
- データフレーム同様に行と列からなる2次元データであるが、全ての要素が同じデータ型でないといけない
- matrix()で生成。nrowとncolでサイズ指定する。
- 各要素に積をとる、内積計算、行または列の統計量をとる などができる
- 参照方法は、データフレーム同様に[でできる
- [で取得すると、ベクトルに変換されるときがあるが、drop=Falseを追記すれば避けられる

In [57]:
m <- matrix(1:9, nrow=3, ncol=3)
print(m)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [58]:
# 各要素に対する積をとる
print(m * 3)

     [,1] [,2] [,3]
[1,]    3   12   21
[2,]    6   15   24
[3,]    9   18   27


In [59]:
# 内積計算
print(m %*% m)

     [,1] [,2] [,3]
[1,]   30   66  102
[2,]   36   81  126
[3,]   42   96  150


In [60]:
# 行ごとの総和
print(rowSums(m))

[1] 12 15 18


In [61]:
# 列ごとの平均
print(colMeans(m))

[1] 2 5 8


In [62]:
# ベクトルへの変換の回避
print(m[ , 3])
print(m[ , 3, drop=FALSE])

[1] 7 8 9
     [,1]
[1,]    7
[2,]    8
[3,]    9
