<a href="https://colab.research.google.com/github/wakamatsuikuma/Essence-of-Machine-Learning-1st-Editon/blob/main/%E3%83%AD%E3%82%B8%E3%82%B9%E3%83%86%E3%82%A3%E3%83%83%E3%82%AF%E5%9B%9E%E5%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.arange(12).reshape(3, 4)
b = np.arange(4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b

array([0, 1, 2, 3])

In [ ]:
c = np.dot(a, b)
c

array([14, 38, 62])

In [ ]:
(1-c)

array([-13, -37, -61])

In [ ]:
d = c * (1-c)
d

array([ -182, -1406, -3782])

In [ ]:
a * b

array([[ 0,  1,  4,  9],
       [ 0,  5, 12, 21],
       [ 0,  9, 20, 33]])

In [ ]:
e = 1/ (b+ 1)
e

array([1.        , 0.5       , 0.33333333, 0.25      ])

In [ ]:
import numpy as np
from scipy import linalg

# 計算が走るように小数点が大きいものは閾値に置き換える
THRESHMIN = 1e-10

# シグモイド関数の定義
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

# ロジスティック回帰の実装 / 重みベクトルの変化量が収束判定以下になるまでニュートン法による更新をくり返す
class LogisticRegression:

# コンストラクタにはトレランス（収束判定）、最大繰り返し数、乱数シード
  def __init__ (self, tol = 0.001, max_iter = 3, random_seed = 0):
    self.tol = tol
    self.max_iter = max_iter
    self.random_state = np.random.RandomState(random_seed)
    self.w_ = None


  def fit(self, X, y):
    self.w_ = self.random_state.randn(X.shape[1] + 1)
    Xtil = np.c_[np.ones(X.shape[0]), X]
    diff = np.inf
    w_prev = self.w_
    iter = 0
    while diff > self.tol and iter < self.max_iter:
      yhat = sigmoid(np.dot(Xtil, self.w_))
      r = np.clip(yhat*(1-yhat), THRESHMIN, np.inf)
      XR = Xtil.T * r
      XRX = np.dot(Xtil.T * r, Xtil)
      w_prev = self.w_
      b = np.dot(XR, np.dot(Xtil, self.w_) - 1 / r * (yhat-y))
      self.w_ = linalg.solve(XRX, b)
      diff = abs(w_prev - self.w_).mean()
      iter += 1
    
  def predict(self, X):
    Xtil = np.c_[np.ones(X.shape[0]), X]
    yhat = sigmoid(np.dot(Xtil, self.w_))
    return np.where(yhat > .5, 1, 0)

In [ ]:
# 乳がんの診断結果のデータ準備
from google.colab import files

uploaded = files.upload()


Saving wdbc.data to wdbc.data


In [ ]:
import csv
import numpy as np

n_test = 100
X = []
y = []
with open("wdbc.data") as fp:
    for row in csv.reader(fp):
        if row[1] == "B":
            y.append(0)
        else:
            y.append(1)
        X.append(row[2:])

y = np.array(y, dtype=np.float64)
X = np.array(X, dtype=np.float64)
y_train = y[:-n_test]
X_train = X[:-n_test]
y_test = y[-n_test:]
X_test = X[-n_test:]

In [ ]:
model = LogisticRegression()
model.fit(X_train, y_train)

y_predict = model.predict(X_test)
n_hits = (y_test == y_predict).sum()
print("Accuracy: {}/{} = {}".format(n_hits, n_test, n_hits / n_test))

Accuracy: 97/100 = 0.97


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: overflow encountered in exp
  if __name__ == '__main__':
